INSERT INTO `einheiten` VALUES (1,'g','g','Gramm',1,1.0,2,0.001);
INSERT INTO `einheiten` VALUES (2,'Kg','Kg','Kilogramm',1,1000.0,2,1.0);
INSERT INTO `einheiten` VALUES (3,'ml','ml','Milliliter',3,1.0,4,0.001);
INSERT INTO `einheiten` VALUES (4,'l','l','Liter',3,1000.0,4,1.0);
INSERT INTO `einheiten` VALUES (5,'TL','TL','Teelöffel',5,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (6,'EL','EL','Esslöffel',6,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (7,'Becher','Becher','Becher',7,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (8,'kl. Dose','kl. Dosen','kleine Dose',8,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (9,'Dose','Dosen','normale Dose',9,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (10,'Tasse','Tassen','Tasse',10,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (11,'MSp','MSp','Messerspitze',11,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (12,'Stck.','Stck.','Stück',12,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (13,'Pck.','Pck.','Packungen',13,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (14,'Würfel','Würfel','Würfel',14,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (15,'Zehe','Zehen','Zehen',15,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (16,'Scheibe','Scheiben','Scheiben',16,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (17,'n.Bel.','n.Bel.','nach Belieben und pers. Geschmack',17,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (18,'Bund','Bund','Bund',18,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (19,'Spritzer','Spritzer','Spritzer',19,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (20,'Stängel','Stängel','Stängel',20,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (21,'cl','cl','Centiliter (10 ml)',3,10.0,4,0.01);
INSERT INTO `einheiten` VALUES (22,'Glas','Gläser','Glas',22,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (23,'etwas','etwas','ein wenig, nach Geschmack',23,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (24,'Blatt','Blätter','Blatt',24,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (25,'cm','cm','Zentimeter',25,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (26,'Flasche','Flaschen','Flasche',26,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (27,'Prise','Prisen','Prise',27,1.0,NULL,NULL);
INSERT INTO `einheiten` VALUES (28,'oz','oz','ounce/Unze (ca. 30g)',1,30.0,2,0.03);
INSERT INTO `einheiten` VALUES (29,'lb','lb','pound (ca. 430g)',1,430.0,2,0.43);
INSERT INTO `einheiten` VALUES (30,'inch','inch','Zoll (2,5 cm)',25,2.5,'',NULL);
INSERT INTO `einheiten` VALUES (31,'Knolle','Knollen','Knollen',31,1,'',NULL);