INSERT INTO `zutaten` VALUES (1,'Amaretto','Amaretto',3,'Handelshof',0.75,4,0.0);
INSERT INTO `zutaten` VALUES (2,'Ananas','Ananas',8,'Handelshof',1.0,8,0.99);
INSERT INTO `zutaten` VALUES (3,'Ananassaft','Ananassaft',21,'Handelshof',1.0,4,0.0);
INSERT INTO `zutaten` VALUES (4,'Anispulver','Anispulver',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (5,'Apfel','Äpfel',1,'Handelshof',1.0,2,0.0);
INSERT INTO `zutaten` VALUES (6,'Apfel, säuerlich','Äpfel, säuerlich',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (7,'Apfelsaft','Apfelsaft',3,'Handelshof',1.0,4,0.0);
INSERT INTO `zutaten` VALUES (8,'Arrak','Arrak',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (9,'Avocado','Avocados',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (10,'Backoblate 7cm Ø','Backoblaten 7cm Ø',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (11,'Backpulver','Backpulver',5,'Handelshof',1.0,13,0.0);
INSERT INTO `zutaten` VALUES (12,'Baguette','Baguettes',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (13,'Baileys','Baileys',21,'Handelshof',0.7,4,11.99);
INSERT INTO `zutaten` VALUES (14,'Basilikum','Basilikum',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (15,'Béchamelsauce','Béchamelsauce',3,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (16,'beurre','beurre',1,'Handelshof',250.0,1,0.0);
INSERT INTO `zutaten` VALUES (17,'beurre (pour le moule)','beurre (pour le moule)',1,'Handelshof',250.0,1,0.0);
INSERT INTO `zutaten` VALUES (18,'beurre remolli','beurre remolli',1,'Handelshof',250.0,1,0.0);
INSERT INTO `zutaten` VALUES (19,'Bittermandelöl','Bittermandelöl',19,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (20,'blancs d´œfs','blancs d´œfs',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (21,'Blätterteig','Blätterteig',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (22,'Blattspinat, gefroren','Blattspinat, gefroren',1,'Handelshof',500.0,1,0.0);
INSERT INTO `zutaten` VALUES (23,'Bohnen, Kidnney','Bohnen, Kidnney',9,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (24,'Bohnenkraut','Bohnenkraut',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (25,'Brandy oder Weinbrand','Brandy oder Weinbrand',21,'Handelshof',0.75,4,0.0);
INSERT INTO `zutaten` VALUES (26,'Braunkuchengewürz','Braunkuchengewürz',11,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (27,'Brühe','Brühe',23,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (28,'Butter','Butter',1,'Handelshof',250.0,1,1.99);
INSERT INTO `zutaten` VALUES (29,'Butter, zerlassen','Butter, zerlassen',1,'Handelshof',250.0,1,1.99);
INSERT INTO `zutaten` VALUES (30,'Buttermilch','Buttermilch',3,'Handelshof',500.0,3,0.0);
INSERT INTO `zutaten` VALUES (31,'Butterschmalz','Butterschmalz',1,'Handelshof',250.0,1,0.0);
INSERT INTO `zutaten` VALUES (32,'Cashewkerne','Cashewkerne',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (33,'Cayennepfeffer','Cayennepfeffer',11,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (34,'Champignons','Champignons',1,'Handelshof',250.0,1,0.99);
INSERT INTO `zutaten` VALUES (35,'Chilipulver','Chilipulver',17,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (36,'Chilischote','Chilischoten',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (37,'Chilischote, rot frisch','Chilischoten, rot frisch',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (38,'Cidre','Cidre',4,'Handelshof',1.0,4,0.0);
INSERT INTO `zutaten` VALUES (39,'Cognac','Cognac',3,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (40,'Couverture','Couverture',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (41,'Couverture, zartbitter','Couverture, zartbitter',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (42,'Cranberries, getrocknet','Cranberries, getrocknet',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (43,'Cream of Coconut','Cream of Coconut',21,'Handelshof',0.75,4,0.0);
INSERT INTO `zutaten` VALUES (44,'crème fleurette (liquide)','crème fleurette (liquide)',3,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (45,'Crème fraîche','Crème fraîche',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (46,'Dinkelschrot','Dinkelschrot',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (47,'Dinkelvollkornmehl','Dinkelvollkornmehl',1,'Handelshof',1.0,2,1.59);
INSERT INTO `zutaten` VALUES (48,'Ei','Eier',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (49,'Eierlikör','Eierlikör',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (50,'Eigelb','Eigelb',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (51,'Eisbergsalat','Eisbergsalate',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (52,'Eiweiß','Eiweiß',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (53,'Emmentaler','Emmentaler',1,'Aldi',100.0,'g',1.29);
INSERT INTO `zutaten` VALUES (54,'Emmentaler, gerieben','Emmentaler, gerieben',1,'Aldi',250.0,1,1.99);
INSERT INTO `zutaten` VALUES (55,'Erdbeere','Erdbeeren',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (56,'Espresso','Espresso',10,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (57,'farine','farine',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (58,'Fischsauce','Fischsauce',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (59,'Frühlingszwiebeln','Frühlingszwiebeln',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (60,'Garam Masala','Garam Masala',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (61,'gehackte Mandeln','gehackte Mandeln',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (62,'Gelatine','Gelatine',28,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (63,'Gelierzucker Extra','Gelierzucker Extra',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (64,'Gewürzgurke','Gewürzgurken',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (65,'Glasnudeln','Glasnudeln',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (66,'Götterspeise, Zitrone','Götterspeise, Zitrone',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (67,'Gouda, gerieben','Gouda, gerieben',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (68,'Gouda, mittelalt','Gouda, mittelalt',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (69,'gousse de vanille (ou arôme)','gousse de vanille (ou arôme)',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (70,'gousses de vanille','gousses de vanille',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (71,'Grieß','Grieß',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (72,'Grieß, hartweizen','Grieß, hartweizen',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (73,'grüne Chilischote','grüne Chilischoten',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (74,'grüne Lasagneplatte','grüne Lasagneplatten',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (75,'Hackfleisch, gem.','Hackfleisch, gem.',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (76,'Hackfleisch, Lamm','Hackfleisch, Lamm',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (77,'Hackfleisch, Rind','Hackfleisch, Rind',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (78,'Haferflocken','Haferflocken',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (79,'Hartkäse','Hartkäse',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (80,'Haselnüsse, gemahlen','Haselnüsse, gemahlen',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (81,'Hefe','Hefe',14,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (82,'heißes Wasser','heißes Wasser',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (83,'Himbeeren, gefroren','Himbeeren, gefroren',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (84,'Honig','Honig',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (85,'Hühnerbrust','Hühnerbrüste',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (86,'Ingwer, frisch','Ingwer, frisch',25,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (87,'Ingwer, gemahlen','Ingwer, gemahlen',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (88,'jaunes d´œfs','jaunes d´œfs',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (89,'Joghurt','Joghurt',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (90,'Joghurt, natur','Joghurt, natur',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (91,'Kaba','Kaba',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (92,'Kakao','Kakao',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (93,'Kakaopulver','Kakaopulver',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (94,'Kapern','Kapern',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (95,'Käse','Käse',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (96,'Käse, gerieben','Käse, gerieben',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (97,'Ketchup','Ketchup',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (98,'Kirschen','Kirschen',22,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (99,'Kirschwasser','Kirschwasser',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (100,'kleine Chilischote','kleine Chilischoten',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (101,'Knoblauch','Knoblauch',15,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (102,'Knoblauchpulver','Knoblauchpulver',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (103,'Kokosfett','Kokosfett',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (104,'Kokosflocken','Kokosflocken',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (105,'Kokosraspeln','Kokosraspeln',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (106,'Koriander','Koriander',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (107,'Koriander, frisch','Koriander, frisch',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (108,'Koriandergrün','Koriandergrün',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (109,'Koriandersamen, gemahlen','Koriandersamen, gemahlen',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (110,'Kräuter','Kräuter',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (111,'Kreuzkümmel, gemahlen','Kreuzkümmel, gemahlen',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (112,'Kümmel','Kümmel',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (113,'Kuverture','Kuverture',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (114,'Lachskotelets je 250 g','Lachskotelets je 250 g',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (115,'lait','lait',3,'Handelshof',1.0,4,0.0);
INSERT INTO `zutaten` VALUES (116,'Lauch','Lauch',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (117,'Lauchstange','Lauchstangen',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (118,'Lebkuchengewürz','Lebkuchengewürz',11,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (119,'Leinsamen','Leinsamen',17,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (120,'levure de boulanger','levure de boulanger',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (121,'Limettensaft','Limettensaft',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (122,'Löffelbiskuit','Löffelbiskuit',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (123,'Lorbeerblatt','Lorbeerblätter',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (124,'Lyoner','Lyoner',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (125,'Magerquark','Magerquark',2,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (126,'Mais','Mais',9,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (127,'Maïzena (farine de maïs)','Maïzena (farine de maïs)',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (128,'Majoran','Majoran',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (129,'Mandarinen','Mandarinen',9,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (130,'Mandelblättchen','Mandelblättchen',1,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (131,'Mandeln','Mandeln',1,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (132,'Mandeln, abgez. gemahlen','Mandeln, abgez. gemahlen',1,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (133,'Mandeln, fein gehackt','Mandeln, fein gehackt',1,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (134,'Mandeln, gemahlen','Mandeln, gemahlen',1,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (135,'Mandeln, ungeschält','Mandeln, ungeschält',1,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (136,'Mangold','Mangold',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (137,'Margarine','Margarine',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (138,'Marmelade','Marmelade',22,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (139,'Marzipanrohmasse','Marzipanrohmasse',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (140,'Mascarpone','Mascarpone',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (141,'Mayonnaise','Mayonnaise',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (142,'Meerrettich','Meerrettich',11,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (143,'Meersalz','Meersalz',17,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (144,'Mehl','Mehl',1,'Handelshof',1.0,2,1.29);
INSERT INTO `zutaten` VALUES (145,'Milch','Milch',3,'Handelshof',1.0,4,1.19);
INSERT INTO `zutaten` VALUES (146,'Miniwindbeutel','Miniwindbeutel',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (147,'Miracel Whip','Miracel Whip',22,'Handelshof',1.0,22,1.29);
INSERT INTO `zutaten` VALUES (148,'Mohn, gemahlen','Mohn, gemahlen',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (149,'Mozzarella','Mozzarella',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (150,'Muskat','Muskat',17,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (151,'œfs','œfs',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (152,'Öl','Öl',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (153,'Olivenöl','Olivenöl',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (154,'Orangeat','Orangeat',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (155,'Oregano','Oregano',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (156,'Paprikapulver, edelsüß','Paprikapulver, edelsüß',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (157,'Paprikapulver, rosen','Paprikapulver, rosen',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (158,'Paprikaschote','Paprikaschoten',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (159,'Paprikaschote, gelb','Paprikaschoten, gelb',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (160,'Paprikaschote, grün','Paprikaschoten, grün',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (161,'Paprikaschote, rot','Paprikaschoten, rot',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (162,'Petersilie','Petersilie',17,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (163,'Petersilie, frisch','Petersilie, frisch',18,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (164,'Pfeffer','Pfeffer',17,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (165,'Philadelphia Frischkäse','Philadelphia Frischkäse',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (166,'Pinienkerne','Pinienkerne',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (167,'Puddingpulver','Puddingpulver',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (168,'Puderzucker','Puderzucker',1,'Handelshof',250.0,1,0.99);
INSERT INTO `zutaten` VALUES (169,'Puderzucker zum Ausrollen','Puderzucker zum Ausrollen',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (170,'Quark','Quark',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (171,'rase de sel fin','rase de sel fin',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (172,'Rhabarber','Rhabarber',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (173,'Roggenschrot','Roggenschrot',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (174,'Roggenschrot (Stufe 3,5)','Roggenschrot (Stufe 3,5)',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (175,'Rohrzucker','Rohrzucker',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (176,'Rohrzucker, braun','Rohrzucker, braun',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (177,'Rosinen','Rosinen',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (178,'Rosmarin','Rosmarin',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (179,'rote Grütze','rote Grütze',3,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (180,'rotes Gelee','rotes Gelee',22,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (181,'Rotwein','Rotwein',3,'Handelshof',0.75,4,0.0);
INSERT INTO `zutaten` VALUES (182,'Rukola','Rukola',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (183,'Rum','Rum',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (184,'Rum, brauner','Rum, brauner',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (185,'Sahne','Sahne',3,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (186,'Sahnesteif','Sahnesteif',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (187,'Salsa-Sauce','Salsa-Sauce',26,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (188,'Salz','Salz',17,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (189,'Sardellenpaste','Sardellenpaste',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (190,'Sardinen ohne Haut','Sardinen ohne Haut',9,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (191,'Sauerkirschen','Sauerkirschen',22,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (192,'Sauerrahm','Sauerrahm',7,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (193,'Sauerteig','Sauerteig',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (194,'saure Sahne','saure Sahne',3,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (195,'Schafskäse','Schafskäse',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (196,'Schinken','Schinken',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (197,'Schinken, gekocht','Schinken, gekocht',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (198,'Schmand','Schmand',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (199,'Schokolade','Schokolade',1,'Handelshof',100.0,1,0.99);
INSERT INTO `zutaten` VALUES (200,'Schokolade, bitter','Schokolade, bitter',1,'Handelshof',100.0,1,0.99);
INSERT INTO `zutaten` VALUES (201,'Schokolade, Herren','Schokolade, Herren',1,'Handelshof',100.0,1,0.99);
INSERT INTO `zutaten` VALUES (202,'Schokolade, weiß','Schokolade, weiß',1,'Handelshof',100.0,1,0.99);
INSERT INTO `zutaten` VALUES (203,'Schokolade, zartbitter','Schokolade, zartbitter',1,'Handelshof',100.0,1,0.99);
INSERT INTO `zutaten` VALUES (204,'Schokoladenglasur','Schokoladenglasur',7,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (205,'Schokoladenglasur, dunkel','Schokoladenglasur, dunkel',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (206,'Schokoladenstreusel, dunkel','Schokoladenstreusel, dunkel',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (207,'Sellerie','Sellerie',22,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (208,'Semmel, alt','Semmeln, alt',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (209,'Senf','Senf',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (210,'Senf, scharf','Senf, scharf',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (211,'Senfkörner','Senfkörner',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (212,'Sherry','Sherry',21,'Handelshof',0.75,4,0.0);
INSERT INTO `zutaten` VALUES (213,'Sojasauce','Sojasauce',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (214,'Sonnenblumenkerne','Sonnenblumenkerne',17,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (215,'Speck','Speck',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (216,'Speck, durchwachsen','Speck, durchwachsen',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (217,'Speisestärke','Speisestärke',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (218,'Stollengewürz','Stollengewürz',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (219,'sucre','sucre',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (220,'sucre en poudre','sucre en poudre',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (221,'Tabasco','Tabasco',19,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (222,'Thymian','Thymian',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (223,'Tintenfisch','Tintenfisch',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (224,'Tintenfischtube','Tintenfischtuben',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (225,'Tomate','Tomaten',12,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (226,'Tomate, fleisch','Tomaten, fleisch',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (227,'Tomaten, Dose','Tomaten, Dosen',9,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (228,'Tomatenketchup','Tomatenketchup',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (229,'Tomatenmark','Tomatenmark',6,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (230,'Tortilla-Chips','Tortilla-Chips',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (231,'Tortillas','Tortillas',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (232,'trockener Weißwein','trockener Weißwein',3,'Handelshof',0.75,4,0.0);
INSERT INTO `zutaten` VALUES (233,'Vanillepuddingpulver','Vanillepuddingpulver',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (234,'Vanilleschote','Vanilleschoten',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (235,'Vanillezucker','Vanillezucker',13,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (236,'Walnusskerne','Walnusskerne',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (237,'Wasser','Wasser',3,'Handelshof',1.0,4,0.0);
INSERT INTO `zutaten` VALUES (238,'Wasser, heiß','Wasser, heiß',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (239,'Wasser, kochend','Wasser, kochend',3,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (240,'Wasser, lauwarm','Wasser, lauwarm',3,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (241,'Weinessig','Weinessig',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (242,'Weizenmehl','Weizenmehl',1,'Handelshof',1.0,2,1.29);
INSERT INTO `zutaten` VALUES (243,'Weizenmehl Typ 550','Weizenmehl Typ 551',1,'Handelshof',1.0,2,1.29);
INSERT INTO `zutaten` VALUES (244,'Weizenmehl, Typ 1050','Weizenmehl, Typ 1051',1,'Handelshof',1.0,2,1.29);
INSERT INTO `zutaten` VALUES (245,'Weizenschrot','Weizenschrot',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (246,'Weizenschrot (Stufe 2)','Weizenschrot (Stufe 2)',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (247,'Whiskey','Whiskey',21,'Handelshof',0.75,4,0.0);
INSERT INTO `zutaten` VALUES (248,'Wiener Grießler','Wiener Grießler',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (249,'Zimt','Zimt',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (250,'Zitronat','Zitronat',1,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (251,'Zitrone','Zitronen',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (252,'Zitrone, abgeriebene Schale','Zitrone, abgeriebene Schale',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (253,'Zitronensaft','Zitronensaft',6,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (254,'Zitronenschale','Zitronenschale',12,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (255,'Zucker','Zucker',5,'Handelshof',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (256,'Zwiebel','Zwiebeln',12,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (257,'Zwiebel, groß','Zwiebeln, groß',12,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (258,'Zwiebel, klein','Zwiebeln, klein',12,'Aldi',NULL,NULL,0.0);
INSERT INTO `zutaten` VALUES (259,'Kartoffel, fest kochend','Kartoffeln, fest kochend',1,'Handelshof',2.5,2,1.79);
INSERT INTO `zutaten` VALUES (260,'Kartoffel, mehlig kochend','Kartoffeln, mehlig kochend',1,'Handelshof',2.5,2,1.79);
INSERT INTO `zutaten` VALUES (261,'Hokkaido Kürbis','Hokkaido Kürbisse',2,'Rewe',1.0,12,1.79);
INSERT INTO `zutaten` VALUES (262,'Karotte, groß','Karotten, groß',12,'Kaufland',1.0,2,NULL);
INSERT INTO `zutaten` VALUES (263,'Karotte','Karotten',12,'Kaufland',1.0,2,NULL);
INSERT INTO `zutaten` VALUES (264,'Currypulver','Currypulver',6,'Kaufland',60.0,1,NULL);
